# API and dashboard configuration
api:
  dashboard: false
  insecure: false

# Enable Healthcheck
ping: {}

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    swarmMode: true

# Traefik Logging
log:
  level: INFO

# Entrypoint
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Challenge DNS
certificatesResolvers:
  myresolver:
    acme:
      email:
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: '0'