gzip on;

gzip_types
    text/plain
    application/javascript
    application/x-javascript
    text/javascript
    application/json
    text/css
    application/xml
    application/xml+rss
    image/svg+xml
    application/font-woff
    application/font-woff2
    application/x-font-ttf
    font/otf
    image/webp;

gzip_comp_level 6;

gzip_proxied any;

gzip_min_length 1024;

gzip_vary on;

gzip_disable "msie6";
